# Generated by Django 3.1.5 on 2021-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('emploee_before_12_1', models.CharField(max_length=100)),
                ('emploee_before_12_2', models.CharField(max_length=100)),
                ('emploee_after_12_1', models.CharField(max_length=100)),
                ('emploee_after_12_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
