# Generated by Django 3.1.5 on 2021-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_check_item_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
