# Generated by Django 3.1.5 on 2021-01-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_check_item_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_item',
            new_name='ReceiptItem',
        ),
    ]
