# Generated by Django 3.1.5 on 2021-01-27 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0004_auto_20210114_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedule_creator', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='emploee_after_12_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploee_after_12_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='emploee_after_12_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploee_after_12_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='emploee_before_12_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploee_before_12_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='emploee_before_12_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploee_before_12_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
