# Generated by Django 3.1.5 on 2021-01-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20210128_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayschedule',
            name='creator',
        ),
    ]
