# Generated by Django 3.1.5 on 2021-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_remove_dayschedule_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
