# Generated by Django 3.1.5 on 2021-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
